import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { launch, openConsumer } from './browser-support.mjs';
const url = process.env.SEEDBANK_URL || 'http://127.0.0.1:5187';
const out = process.env.UI_EVIDENCE_DIR || 'artifacts/ui';
await mkdir(out, { recursive: true });
const browser = await launch();
const errors = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1160 }, deviceScaleFactor: 1, reducedMotion: 'reduce', acceptDownloads: true });
  const page = await context.newPage(); page.on('pageerror', e => errors.push(e.message));
  await page.goto(url, { waitUntil: 'networkidle' });
  await page.getByRole('button', { name: 'Play animation', exact: true }).waitFor();
  await page.getByLabel('Renderer backend').selectOption('webgl2');
  await page.getByRole('button', { name: 'Play animation', exact: true }).waitFor({ state: 'visible' });
  await page.waitForFunction(() => !document.querySelector('.play-button').disabled);
  assert.equal(await page.getByRole('button', { name: 'Pause animation', exact: true }).count(), 0, 'Reduced motion should start frozen');
  await page.screenshot({ path: `${out}/viewer-desktop.png`, fullPage: true });
  await page.getByRole('tab', { name: /Archive/ }).click();
  await page.getByRole('button', { name: /Phosphor crt/ }).click();
  await page.getByLabel('Preset name').fill('Stored signal');
  await page.getByLabel('Seed', { exact: true }).fill('543');
  await page.getByLabel('Intensity', { exact: true }).fill('1.45');
  await page.getByLabel('Go to time in seconds').fill('4.5');
  await page.getByRole('button', { name: /Save preset/ }).click();
  await page.getByRole('tab', { name: /Saved/ }).click();
  await page.getByRole('button', { name: /Stored signal seed 543/ }).waitFor();
  console.log('Checking persisted presets');
  await page.reload({ waitUntil: 'networkidle' });
  await page.getByRole('tab', { name: /Saved/ }).click();
  await page.getByRole('button', { name: /Stored signal seed 543/ }).click();
  assert.equal(await page.getByLabel('Seed', { exact: true }).inputValue(), '543');
  assert.equal(await page.getByLabel('Intensity', { exact: true }).inputValue(), '1.45');
  assert.equal(await page.getByLabel('Go to time in seconds').inputValue(), '4.5');
  await page.getByLabel('Renderer backend').selectOption('webgl2');
  await page.waitForFunction(() => !document.querySelector('.play-button').disabled);
  await page.getByRole('tab', {name:'Export ↗',exact:true}).click();
  const recipeEvent = page.waitForEvent('download'); await page.getByRole('button', { name: 'Recipe ↓', exact: true }).click();
  const recipeDownload = await recipeEvent; await recipeDownload.saveAs(`${out}/exported-recipe.json`);
  const exported = JSON.parse(await readFile(`${out}/exported-recipe.json`, 'utf8'));
  assert.equal(exported.seed, 543); assert.equal(exported.time, 4.5); assert.equal(exported.family, 'phosphor');
  const pngEvent = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export PNG ↗', exact: true }).click();
  const pngDownload = await pngEvent; await pngDownload.saveAs(`${out}/exported-frame.png`);
  const png = await readFile(`${out}/exported-frame.png`);
  assert.equal(png.toString('hex', 0, 8), '89504e470d0a1a0a');
  const size = await page.locator('canvas').evaluate(canvas => ({ width: canvas.width, height: canvas.height }));
  console.log('Checking export reproduction');
  const { page: consumer, errors: consumerErrors } = await openConsumer(browser, url, 'webgl2');
  const reproduced = await consumer.evaluate(async ({ recipe, width, height }) => {
    const runtime = window.seedbank.runtime; runtime.setRecipe(recipe); runtime.resize(width, height); await runtime.compile();
    const blob = await runtime.capture();
    return new Promise(resolve => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.readAsDataURL(blob); });
  }, { recipe: exported, ...size });
  assert.equal(createHash('sha256').update(Buffer.from(reproduced.split(',')[1], 'base64')).digest('hex'), createHash('sha256').update(png).digest('hex'), 'Independent consumer must reproduce exported PNG from exported recipe at the same dimensions/backend');
  assert.deepEqual(consumerErrors, []);
  await consumer.close();
  console.log('Checking import and playback');
  await page.locator('input[type=file]').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"schemaVersion":99}') });
  await page.getByRole('status').filter({ hasText: 'Import failed' }).waitFor();
  await page.locator('input[type=file]').setInputFiles(`${out}/exported-recipe.json`);
  await page.getByRole('status').filter({ hasText: 'Recipe imported' }).waitFor();
  assert.equal(await page.getByLabel('Seed', { exact: true }).inputValue(), '543');
  await page.getByRole('button', { name: 'Play animation', exact: true }).click();
  const before = await page.locator('.time-readout').innerText();
  await page.waitForFunction(before => document.querySelector('.time-readout').innerText !== before, before);
  await page.getByRole('button', { name: 'Freeze this frame' }).click();
  const frozen = await page.getByLabel('Go to time in seconds').inputValue();
  assert.ok(Number(frozen) >= 4.5);
  console.log('Checking measurement');
  await page.getByRole('button', { name: /Measure render/ }).click();
  await page.getByRole('button', { name: 'Report ↓' }).waitFor();
  await page.getByRole('tab', { name: /Archive/ }).click();
  await page.getByRole('button', { name: /Halftone print/ }).click();
  await page.screenshot({ path: `${out}/viewer-halftone.png`, fullPage: true });
  await page.getByRole('button', { name: /Caustics water/ }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: `${out}/viewer-mobile.png`, fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile page must not overflow horizontally');
  await page.getByRole('tab', { name: /Saved/ }).click();
  await page.getByRole('button', { name: 'Remove Stored signal', exact: true }).click();
  await page.reload({ waitUntil: 'networkidle' });
  await page.getByRole('tab', { name: /Saved/ }).click();
  await page.getByText('A place for the good ones.').waitFor();
  assert.deepEqual(errors, []);
  const report = { checkedAt: new Date().toISOString(), browser: await browser.version(), checks: ['reduced-motion starts frozen', 'WebGL2 explicit selection', 'save/reload/reopen all recipe inputs', 'recipe download', 'PNG download', 'independent consumer reproduces exported recipe and PNG exactly at same dimensions/backend', 'invalid import rejected', 'valid import reopens', 'animation advances and freeze updates time', 'CPU measurement completes', '390px mobile no overflow', 'delete persists across reload'], errors };
  await writeFile(`${out}/report.json`, JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); }
