import type { Recipe } from './recipes';

/** Logic studies 91–100: registry data only (no three.js imports). */
export const logicFamilies = ['munch', 'butterfly', 'hilbert', 'residual', 'catmap', 'compass', 'collage', 'stutter', 'quadtree', 'misregister'] as const;
export type LogicFamily = typeof logicFamilies[number];
export const isLogic = (family: string): family is LogicFamily => logicFamilies.some(value => value === family);
export const logicInfo: Record<LogicFamily, { name: string; subtitle: string; description: string; detail: string; number: string }> = {
  munch: { name: 'Munch', subtitle: 'Every bit takes its own road.', description: 'Bent bitwise textures are torn into four bit planes that travel in different directions and are resown at random, leaving XOR fringes and flat inverted islands.', detail: 'Bend', number: '91' },
  butterfly: { name: 'Butterfly', subtitle: 'The address lines are crossed.', description: 'Tiles shuffle their pixels through a shifting butterfly network: coordinate bits swap, cross and mirror every frame, so blocks of every size trade places mid-drift.', detail: 'Bit range', number: '92' },
  hilbert: { name: 'Hilbert', subtitle: 'One thread through every pixel.', description: 'Pixels sort and slide along tiled space-filling curves whose segments run in opposing directions, so islands unravel into nested U-turns and hairpins.', detail: 'Segment length', number: '93' },
  residual: { name: 'Residual', subtitle: 'The error is the image.', description: 'Quantization error diffuses downstream through a turning cone while the quantized picture is carried forward, so wormlike dither patterns swim through torn islands.', detail: 'Worm length', number: '94' },
  catmap: { name: 'Cat map', subtitle: 'Stretched, folded, shuffled.', description: 'Square lenses apply a chaotic toral map to whole blocks of history while their cores shred it pixel by pixel; shear currents drag the pieces between visits.', detail: 'Block size', number: '95' },
  compass: { name: 'Compass', subtitle: 'The tone chooses the direction.', description: 'Every pixel pulls from the neighbour its own value points to, so tonal bands flow in their own directions and knot where the sectors meet.', detail: 'Turns', number: '96' },
  collage: { name: 'Collage', subtitle: 'Copies of copies of copies.', description: 'Shrunk, turned and flipped copies of the whole picture are pasted back into it every frame, so torn islands regress into self-similar cascades.', detail: 'Copy count', number: '97' },
  stutter: { name: 'Stutter', subtitle: 'Nothing updates at the same time.', description: 'Each pixel runs on its own clock and jumps by everything it missed when it wakes, so moving edges dissolve into asynchronous scatter and re-solidify at rest.', detail: 'Longest hold', number: '98' },
  quadtree: { name: 'Quadtree', subtitle: 'Resolution follows the motion.', description: 'Calm regions collapse into large flat blocks while activity subdivides them down to single cells, so the mosaic refines and coarsens as islands drift through it.', detail: 'Sensitivity', number: '99' },
  misregister: { name: 'Misregister', subtitle: 'Four inks, four currents.', description: 'Each palette role is a separate ink layer with its own current and erosion; layers occlude by a priority that keeps changing, like a print that never lines up.', detail: 'Layer detail', number: '100' },
};
export const logicPresets: Recipe[] = [
  { schemaVersion: 1, generatorVersion: '1.9.0', id: 'logic-munch', name: 'Munch / logic study', kind: 'animated-shader', family: 'munch', seed: 31337, time: 3.25, parameters: { scale: 2.6, speed: 1.4, intensity: 1.1, detail: 0.6 }, palette: ['#eef0e8', '#1a4dff', '#141a2a', '#6b7a99', '#c9ff3a'], tags: ['logic', 'bitwise', 'grid only', 'scanlines', 'crisp'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.9.0', id: 'logic-butterfly', name: 'Butterfly / logic study', kind: 'animated-shader', family: 'butterfly', seed: 4097, time: 3.25, parameters: { scale: 2.6, speed: 1.4, intensity: 1.1, detail: 0.55 }, palette: ['#101418', '#ff3d81', '#f2f4f0', '#3c4a5e', '#3cf2c8'], tags: ['logic', 'permutation', 'grid only', 'crisp'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.9.0', id: 'logic-hilbert', name: 'Hilbert / logic study', kind: 'animated-shader', family: 'hilbert', seed: 46341, time: 3.25, parameters: { scale: 2.6, speed: 1.4, intensity: 1.1, detail: 0.6 }, palette: ['#f3ead8', '#e8481f', '#1f1a1a', '#8a5a3c', '#2f6fd8'], tags: ['logic', 'space-filling curve', 'grid only', 'crisp'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.9.0', id: 'logic-residual', name: 'Residual / logic study', kind: 'animated-shader', family: 'residual', seed: 65521, time: 3.25, parameters: { scale: 2.6, speed: 1.4, intensity: 1.1, detail: 0.6 }, palette: ['#e9e4d8', '#0057ff', '#101010', '#7a7f8a', '#ff5c8a'], tags: ['logic', 'error diffusion', 'crisp'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.9.0', id: 'logic-catmap', name: 'Cat map / logic study', kind: 'animated-shader', family: 'catmap', seed: 2584, time: 3.25, parameters: { scale: 2.6, speed: 1.4, intensity: 1.1, detail: 0.55 }, palette: ['#0c1020', '#ffb000', '#e8ecf4', '#2a3a6e', '#ff4d4d'], tags: ['logic', 'chaotic map', 'grid only', 'crisp'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.9.0', id: 'logic-compass', name: 'Compass / logic study', kind: 'animated-shader', family: 'compass', seed: 12289, time: 3.25, parameters: { scale: 2.6, speed: 1.4, intensity: 1.1, detail: 0.5 }, palette: ['#eef4ee', '#00857a', '#1a1f1c', '#7fb8a8', '#ff7a1a'], tags: ['logic', 'self-steered', 'crisp'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.9.0', id: 'logic-collage', name: 'Collage / logic study', kind: 'animated-shader', family: 'collage', seed: 28657, time: 3.25, parameters: { scale: 2.6, speed: 1.4, intensity: 1.1, detail: 0.7 }, palette: ['#f4efe6', '#7b3fe4', '#1c1633', '#c6b3ea', '#ffd23f'], tags: ['logic', 'iterated maps', 'radial', 'crisp'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.9.0', id: 'logic-stutter', name: 'Stutter / logic study', kind: 'animated-shader', family: 'stutter', seed: 54321, time: 3.25, parameters: { scale: 2.6, speed: 1.4, intensity: 1.1, detail: 0.65 }, palette: ['#1a1c22', '#c6ff00', '#f5f5f5', '#4a4f5a', '#ff2bd6'], tags: ['logic', 'asynchronous', 'scanlines', 'crisp'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.9.0', id: 'logic-quadtree', name: 'Quadtree / logic study', kind: 'animated-shader', family: 'quadtree', seed: 7919, time: 3.25, parameters: { scale: 2.6, speed: 1.4, intensity: 1.1, detail: 0.55 }, palette: ['#e6e8ee', '#ff3d00', '#1d2330', '#8b96ad', '#00c2ff'], tags: ['logic', 'mosaic', 'grid only', 'crisp'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.9.0', id: 'logic-misregister', name: 'Misregister / logic study', kind: 'animated-shader', family: 'misregister', seed: 40503, time: 3.25, parameters: { scale: 2.6, speed: 1.4, intensity: 1.1, detail: 0.6 }, palette: ['#f6f1e8', '#ff2f8f', '#0a1f5c', '#26b2a8', '#ffd21f'], tags: ['logic', 'ink layers', 'crisp'], review: 'candidate' },
];
