import type { Recipe } from './recipes';

/** Matter studies 81–90: registry data only (no three.js imports). */
export const matterFamilies = ['ripple', 'agate', 'grain', 'borealis', 'lightning', 'swarm', 'strata', 'cumulus', 'phyllotaxis', 'smoke'] as const;
export type MatterFamily = typeof matterFamilies[number];
export const isMatter = (family: string): family is MatterFamily => matterFamilies.some(value => value === family);
export const matterInfo: Record<MatterFamily, { name: string; subtitle: string; description: string; detail: string; number: string }> = {
  "ripple": { name: "Ripple", subtitle: "Rain on a tiled pool.", description: "Raindrops start damped, interfering rings that bend a tiled pool floor beneath a wandering caustic net.", detail: "Rainfall", number: '81' },
  "agate": { name: "Agate", subtitle: "Layers that grow inward.", description: "Banded nodules lay down fortification layers that flow toward faceted crystal cores, their rinds wandering through speckled host rock.", detail: "Band count", number: '82' },
  "grain": { name: "Grain", subtitle: "Rings, knots and a moving saw.", description: "Planks slide past each other while growth rings arch and swirl around knots; a passing saw leaves arcs that ride away with the boards.", detail: "Ring density", number: '83' },
  "borealis": { name: "Borealis", subtitle: "Curtains of charged light.", description: "Two folding curtains of fine vertical rays ripple, pulse and shimmer upward from their bright lower edges.", detail: "Ray density", number: '84' },
  "lightning": { name: "Lightning", subtitle: "The sky picks a path.", description: "Jagged branching strikes flicker through return strokes, light the cloud deck and leave a stepped afterglow and fading ghosts.", detail: "Branching", number: '85' },
  "swarm": { name: "Swarm", subtitle: "Hundreds decide together.", description: "Hundreds of single-pixel agents ride a shifting flow; groups split, rejoin and scatter from sudden disturbances, trailing light.", detail: "Swarm density", number: '86' },
  "strata": { name: "Strata", subtitle: "Rock remembers every flood.", description: "Folded sediment bands, laminated, speckled, pebbled and cross-bedded, sink through a faulted section beneath an eroded skyline.", detail: "Lamination", number: '87' },
  "cumulus": { name: "Cumulus", subtitle: "Weather in flat pixels.", description: "Three parallax layers of lobed pixel-art cumulus drift, grow and thin away beneath a dithered sun.", detail: "Cloud cover", number: '88' },
  "phyllotaxis": { name: "Phyllotaxis", subtitle: "Every seed at the golden angle.", description: "Golden-angle seed heads turn and swell inside rings of petals; rim seeds come loose and drift away on the wind.", detail: "Seed count", number: '89' },
  "smoke": { name: "Smoke", subtitle: "Thin columns, then turbulence.", description: "Thin plumes rise from wandering sources, curl in a divergence-free current and billow into dithered haze.", detail: "Turbulence", number: '90' },
};
export const matterPresets: Recipe[] = [
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "matter-ripple", "name": "Ripple / matter study", "kind": "animated-shader", "family": "ripple", "seed": 24062, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.45}, "palette": ["#1f86ad", "#c9f6ff", "#0d3b57", "#59b8d6", "#ffffff"], "tags": ["matter", "natural", "crisp", "water"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "matter-agate", "name": "Agate / matter study", "kind": "animated-shader", "family": "agate", "seed": 51358, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.2, "intensity": 1.1, "detail": 0.6}, "palette": ["#1b2a41", "#5fa8d3", "#e8eef2", "#324a5f", "#cae9ff"], "tags": ["matter", "natural", "crisp", "mineral"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "matter-grain", "name": "Grain / matter study", "kind": "animated-shader", "family": "grain", "seed": 8722, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.55}, "palette": ["#3b2416", "#c98b4f", "#f1d9b5", "#7a4a2a", "#e4b27a"], "tags": ["matter", "natural", "crisp", "material"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "matter-borealis", "name": "Borealis / matter study", "kind": "animated-shader", "family": "borealis", "seed": 34210, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.2, "intensity": 1.1, "detail": 0.6}, "palette": ["#050d1a", "#2dffb3", "#b388ff", "#1b6f6a", "#7df9ff"], "tags": ["matter", "natural", "crisp", "sky"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "matter-lightning", "name": "Lightning / matter study", "kind": "animated-shader", "family": "lightning", "seed": 60574, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.6}, "palette": ["#140c1f", "#ff9f1c", "#e0e7ff", "#5b2a86", "#ffd6a5"], "tags": ["matter", "natural", "crisp", "sky"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "matter-swarm", "name": "Swarm / matter study", "kind": "animated-shader", "family": "swarm", "seed": 12880, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.2, "intensity": 1.1, "detail": 0.6}, "palette": ["#0b1410", "#ffe066", "#c6f68d", "#2d4a3a", "#ff9f43"], "tags": ["matter", "natural", "crisp", "points"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "matter-strata", "name": "Strata / matter study", "kind": "animated-shader", "family": "strata", "seed": 47194, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.55}, "palette": ["#f2e3c6", "#d9a05b", "#5c3d2e", "#b86f3c", "#8a9a5b"], "tags": ["matter", "natural", "crisp", "mineral"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "matter-cumulus", "name": "Cumulus / matter study", "kind": "animated-shader", "family": "cumulus", "seed": 29662, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.55}, "palette": ["#3d6fa8", "#ffe8d6", "#f7f4ef", "#9fb8d9", "#f4a261"], "tags": ["matter", "natural", "crisp", "sky"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "matter-phyllotaxis", "name": "Phyllotaxis / matter study", "kind": "animated-shader", "family": "phyllotaxis", "seed": 5584, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.6}, "palette": ["#1a2e1a", "#f4d35e", "#ee964b", "#6a994e", "#f95738"], "tags": ["matter", "natural", "crisp", "radial"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "matter-smoke", "name": "Smoke / matter study", "kind": "animated-shader", "family": "smoke", "seed": 42014, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.2, "intensity": 1.1, "detail": 0.6}, "palette": ["#0e0e12", "#8a8fa3", "#e8e6e3", "#3b3d4a", "#c9a227"], "tags": ["matter", "natural", "crisp", "flow"], "review": "candidate"},
];
