import type { Recipe } from './recipes';

/** Pattern studies 61–70: registry data only (no three.js imports). */
export const patternFamilies = ['tartan', 'ikat', 'truchet', 'bauhaus', 'marbling', 'rosette', 'bargello', 'vega', 'kaleidoscope', 'hatch'] as const;
export type PatternFamily = typeof patternFamilies[number];
export const isPattern = (family: string): family is PatternFamily => patternFamilies.some(value => value === family);
export const patternInfo: Record<PatternFamily, { name: string; subtitle: string; description: string; detail: string; number: string }> = {
  "tartan": { name: "Tartan", subtitle: "The sett keeps slipping.", description: "A twill sett of crossing warp and weft stripes; threads drift at their own pace and snag into pulled runs.", detail: "Sett density", number: '61' },
  "ikat": { name: "Ikat", subtitle: "Dye that moved before the weave.", description: "Stepped lozenges bleed sideways along their thread bundles; bundles drift, motif columns are re-dyed and events stretch rows into hard streaks.", detail: "Motif steps", number: '62' },
  "truchet": { name: "Truchet", subtitle: "Every tile turns the path.", description: "Quarter-arc tiles form one continuous maze; travelling fronts flip tiles and reroute it while dashes run along the paths.", detail: "Path weight", number: '63' },
  "bauhaus": { name: "Bauhaus", subtitle: "A grid that will not sit still.", description: "Quarter discs, half moons, bars and rings snap through quarter turns in cascading waves while whole rows step along like conveyor belts.", detail: "Grid division", number: '64' },
  "marbling": { name: "Marbling", subtitle: "Combed through floating color.", description: "Floating bands of paint are drawn through three combs into chevrons and feathers; stone drops push the whole pattern outward.", detail: "Comb teeth", number: '65' },
  "rosette": { name: "Rosette", subtitle: "Three screens, never in register.", description: "Three rotated halftone screens print hard pixel dots that drift out of register, swell with the tone field and slur where the sheet slips.", detail: "Screen ruling", number: '66' },
  "bargello": { name: "Bargello", subtitle: "A flame stitch climbing the canvas.", description: "Upright stitches step through zigzag flame bands; the peaks change shape, spires rise from events and the colors climb.", detail: "Stitch length", number: '67' },
  "vega": { name: "Vega", subtitle: "The grid bulges toward you.", description: "An op-art checkerboard of discs swells under two moving lenses; magnified discs square off and step through the palette.", detail: "Bulge", number: '68' },
  "kaleidoscope": { name: "Kaleidoscope", subtitle: "Six mirrors, one moving field.", description: "Mirrored wedges fold drifting glass pieces into a turning mandala with leading, bead rings and a wandering center.", detail: "Mirror count", number: '69' },
  "hatch": { name: "Hatch", subtitle: "An engraving that keeps redrawing itself.", description: "Engraved lines swell and thin with tone, cross-hatch in the shadows and bend with form; spot colors print under the lines.", detail: "Line pitch", number: '70' },
};
export const patternPresets: Recipe[] = [
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "pattern-tartan", "name": "Tartan / pattern study", "kind": "animated-shader", "family": "tartan", "seed": 24042, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.6}, "palette": ["#1f3b2c", "#c8102e", "#0d1b2a", "#274c77", "#f2c14e"], "tags": ["pattern", "ornament", "crisp", "grid only"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "pattern-ikat", "name": "Ikat / pattern study", "kind": "animated-shader", "family": "ikat", "seed": 51338, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.2, "intensity": 1.1, "detail": 0.6}, "palette": ["#f2e8d5", "#c1440e", "#1d3557", "#e09f3e", "#335c67"], "tags": ["pattern", "ornament", "crisp", "textile"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "pattern-truchet", "name": "Truchet / pattern study", "kind": "animated-shader", "family": "truchet", "seed": 8702, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.2, "intensity": 1.2, "detail": 0.55}, "palette": ["#101820", "#f2aa4c", "#e9e4d8", "#2e86ab", "#e4572e"], "tags": ["pattern", "ornament", "crisp", "tiling"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "pattern-bauhaus", "name": "Bauhaus / pattern study", "kind": "animated-shader", "family": "bauhaus", "seed": 34190, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.45}, "palette": ["#efe8d8", "#d62828", "#1d1d1b", "#f2b134", "#1f4e9a"], "tags": ["pattern", "ornament", "crisp", "tiling"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "pattern-marbling", "name": "Marbling / pattern study", "kind": "animated-shader", "family": "marbling", "seed": 60554, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.2, "intensity": 1.1, "detail": 0.5}, "palette": ["#f4ecd8", "#1b4f72", "#9b2335", "#d4a017", "#2e8b57"], "tags": ["pattern", "ornament", "crisp", "print"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "pattern-rosette", "name": "Rosette / pattern study", "kind": "animated-shader", "family": "rosette", "seed": 12860, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.2, "intensity": 1.1, "detail": 0.55}, "palette": ["#f7f3e8", "#00a0c6", "#e0218a", "#1a1a1a", "#ffd400"], "tags": ["pattern", "ornament", "crisp", "print"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "pattern-bargello", "name": "Bargello / pattern study", "kind": "animated-shader", "family": "bargello", "seed": 47174, "time": 3.25, "parameters": {"scale": 3.0, "speed": 1.0, "intensity": 1.1, "detail": 0.5}, "palette": ["#2b193d", "#ff7f51", "#f2d0a4", "#c44569", "#6c9a8b"], "tags": ["pattern", "ornament", "crisp", "textile"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "pattern-vega", "name": "Vega / pattern study", "kind": "animated-shader", "family": "vega", "seed": 29642, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.2, "intensity": 1.1, "detail": 0.55}, "palette": ["#111111", "#e63946", "#f1faee", "#457b9d", "#a8dadc"], "tags": ["pattern", "ornament", "crisp", "op art"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "pattern-kaleidoscope", "name": "Kaleidoscope / pattern study", "kind": "animated-shader", "family": "kaleidoscope", "seed": 5564, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.1, "intensity": 1.1, "detail": 0.6}, "palette": ["#0b0c2a", "#ff4ecd", "#ffd23f", "#3a86ff", "#06d6a0"], "tags": ["pattern", "ornament", "crisp", "radial"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "pattern-hatch", "name": "Hatch / pattern study", "kind": "animated-shader", "family": "hatch", "seed": 41994, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.2, "intensity": 1.1, "detail": 0.55}, "palette": ["#f0e9dc", "#b3312c", "#1b1b1f", "#4a5a6a", "#d9a441"], "tags": ["pattern", "ornament", "crisp", "linework"], "review": "candidate"},
];
