import type { Recipe } from './recipes';

/** Raster studies 71–80: registry data only (no three.js imports). */
export const rasterFamilies = ['pyre', 'tunnel', 'warp', 'copper', 'vectorscope', 'flipdot', 'voxel', 'mode7', 'orbit', 'twister'] as const;
export type RasterFamily = typeof rasterFamilies[number];
export const isRaster = (family: string): family is RasterFamily => rasterFamilies.some(value => value === family);
export const rasterInfo: Record<RasterFamily, { name: string; subtitle: string; description: string; detail: string; number: string }> = {
  "pyre": { name: "Pyre", subtitle: "Heat climbs and forgets.", description: "Rising pixel fire: heat is fed from the base and from flares, carved into tongues by a cooling map that climbs with it, and stepped through every palette role.", detail: "Flame height", number: '71' },
  "tunnel": { name: "Tunnel", subtitle: "Falling forward through the pattern.", description: "A brick-tiled polar tunnel morphs between round and square while its vanishing point wanders and bends; lamp pulses race toward you through dithered fog.", detail: "Tile motif", number: '72' },
  "warp": { name: "Warp", subtitle: "The stars become lines.", description: "A starfield streaks out of a drifting vanishing point; streaks lengthen in warp bursts, stall to points and take their color from depth.", detail: "Star density", number: '73' },
  "copper": { name: "Copper", subtitle: "Raster bars with somewhere to be.", description: "Dithered raster bars swing between random heights, passing in front of and behind a sine-waved scroller, and leave hard trails that dissolve.", detail: "Bar count", number: '74' },
  "vectorscope": { name: "Vectorscope", subtitle: "A beam that never lifts.", description: "A single phosphor beam draws Lissajous and harmonograph figures over a graticule; each new figure morphs out of the fading glow of the last.", detail: "Harmonics", number: '75' },
  "flipdot": { name: "Flipdot", subtitle: "Every disc has two faces.", description: "A flip-disc panel of drifting blobs, sweeping fronts and a scrolling glyph marquee; each disc turns over edge-first when its face changes.", detail: "Disc density", number: '76' },
  "voxel": { name: "Voxel", subtitle: "Low flight over pixel terrain.", description: "A raycast heightmap landscape: banking low flight over slope-lit hills, water and snow bands, under a dithered horizon glow.", detail: "Terrain relief", number: '77' },
  "mode7": { name: "Mode 7", subtitle: "A plane that runs to the horizon.", description: "A perspective tile plane turns and glides toward a hard horizon under a striped sun and a wrapped skyline; tile regions rewrite as slow fronts pass.", detail: "Tile pattern", number: '78' },
  "orbit": { name: "Orbit", subtitle: "Points on invisible bodies.", description: "A rotating 3D point cloud morphs between sphere, knot, rings, helix, cube and Lissajous forms; pixel dots take depth colors and leave dotted trails.", detail: "Point density", number: '79' },
  "twister": { name: "Twister", subtitle: "A column that will not stop turning.", description: "Four-faced columns corkscrew and sway at shifting rates; each face is a flat color with Bayer-stepped shading and hard seams.", detail: "Column count", number: '80' },
};
export const rasterPresets: Recipe[] = [
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "raster-pyre", "name": "Pyre / raster study", "kind": "animated-shader", "family": "pyre", "seed": 24052, "time": 12, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.6}, "palette": ["#0b0302", "#ff4d17", "#ffd36b", "#a3160f", "#fff4d2"], "tags": ["raster", "demoscene", "crisp", "fire"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "raster-tunnel", "name": "Tunnel / raster study", "kind": "animated-shader", "family": "tunnel", "seed": 51348, "time": 3.25, "parameters": {"scale": 3.2, "speed": 1.0, "intensity": 1.1, "detail": 0.6}, "palette": ["#0d0221", "#0abdc6", "#ea00d9", "#133e7c", "#711c91"], "tags": ["raster", "demoscene", "crisp", "radial"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "raster-warp", "name": "Warp / raster study", "kind": "animated-shader", "family": "warp", "seed": 8712, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.2, "intensity": 1.1, "detail": 0.6}, "palette": ["#05060f", "#5b6cff", "#f4f1ff", "#27306b", "#ffe29a"], "tags": ["raster", "demoscene", "crisp", "radial"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "raster-copper", "name": "Copper / raster study", "kind": "animated-shader", "family": "copper", "seed": 34200, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.55}, "palette": ["#120a1f", "#00e5ff", "#ff4ecd", "#3a2b6b", "#fdf5a6"], "tags": ["raster", "demoscene", "crisp", "scanlines"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "raster-vectorscope", "name": "Vectorscope / raster study", "kind": "animated-shader", "family": "vectorscope", "seed": 60564, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.2, "detail": 0.5}, "palette": ["#050807", "#1aff8c", "#b7ffd6", "#1f6b4a", "#ffb000"], "tags": ["raster", "demoscene", "crisp", "linework"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "raster-flipdot", "name": "Flipdot / raster study", "kind": "animated-shader", "family": "flipdot", "seed": 12870, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.6}, "palette": ["#141414", "#ffd400", "#f5f5f0", "#3a3a3a", "#ff1f5a"], "tags": ["raster", "demoscene", "crisp", "grid only"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "raster-voxel", "name": "Voxel / raster study", "kind": "animated-shader", "family": "voxel", "seed": 47184, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.55}, "palette": ["#17193b", "#3fb8af", "#e9c46a", "#b5535d", "#fdf0d5"], "tags": ["raster", "demoscene", "crisp", "landscape"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "raster-mode7", "name": "Mode 7 / raster study", "kind": "animated-shader", "family": "mode7", "seed": 29652, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.5}, "palette": ["#1d3557", "#e63946", "#f1faee", "#457b9d", "#ffb703"], "tags": ["raster", "demoscene", "crisp", "perspective"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "raster-orbit", "name": "Orbit / raster study", "kind": "animated-shader", "family": "orbit", "seed": 5574, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.3, "detail": 0.6}, "palette": ["#0a0612", "#ff2e88", "#7df9ff", "#3d1a5b", "#f5f3ff"], "tags": ["raster", "demoscene", "crisp", "points"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.9.0", "id": "raster-twister", "name": "Twister / raster study", "kind": "animated-shader", "family": "twister", "seed": 42004, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.0, "intensity": 1.1, "detail": 0.5}, "palette": ["#fff6e5", "#ff3d7f", "#1e3cc8", "#ffb400", "#00c49a"], "tags": ["raster", "demoscene", "crisp", "3d"], "review": "candidate"},
];
