import { patternFamilies, isPattern, patternInfo, patternPresets, type PatternFamily } from './pattern-meta.ts';
import { rasterFamilies, isRaster, rasterInfo, rasterPresets, type RasterFamily } from './raster-meta.ts';
import { matterFamilies, isMatter, matterInfo, matterPresets, type MatterFamily } from './matter-meta.ts';
export { patternFamilies, isPattern, rasterFamilies, isRaster, matterFamilies, isMatter, type PatternFamily, type RasterFamily, type MatterFamily };
export const RECIPE_VERSION = 1 as const;
export const GENERATOR_VERSION = '1.9.0' as const;
export type GeneratorVersion = '1.0.0' | '1.1.0' | '1.2.0' | '1.3.0' | '1.4.0' | '1.5.0' | '1.6.0' | '1.7.0' | '1.8.0' | typeof GENERATOR_VERSION;
const generatorVersions: readonly string[] = ['1.0.0', '1.1.0', '1.2.0', '1.3.0', '1.4.0', '1.5.0', '1.6.0', '1.7.0', '1.8.0', GENERATOR_VERSION];
/** Pattern, raster and matter studies (61–90) share the kit lifecycle and generator 1.9.0. */
export const isKit = (family: string) => isPattern(family) || isRaster(family) || isMatter(family);
export const pixelSorterFamilies = ['crosscurrent', 'undertow', 'downpour', 'faultline'] as const;
export type PixelSorterFamily = typeof pixelSorterFamilies[number];
export const isPixelSorter = (family: string): family is PixelSorterFamily => pixelSorterFamilies.some(value => value === family);
export const departureFamilies = ['rotor', 'slingshot', 'cell-division', 'shockfront', 'filament'] as const;
export type DepartureFamily = typeof departureFamilies[number];
export const isDeparture = (family: string): family is DepartureFamily => departureFamilies.some(value => value === family);
export const damageFamilies = ['row-collapse', 'column-shear', 'address-drift', 'staircase', 'dead-channel', 'puncture', 'pressure-leak', 'shatter', 'delamination', 'raster-bloom'] as const;
export type DamageFamily = typeof damageFamilies[number];
export const isDamage = (family: string): family is DamageFamily => damageFamilies.some(value => value === family);
export const entropyFamilies = ['rift', 'parcel', 'tangle', 'spall', 'dendrite', 'suture', 'flock', 'palisade', 'alveoli', 'confluence'] as const;
export type EntropyFamily = typeof entropyFamilies[number];
export const isEntropy = (family: string): family is EntropyFamily => entropyFamilies.some(value => value === family);
export const intricacyFamilies = ["intaglio", "braid", "scrim", "guilloche", "imbricate", "capillary", "palimpsest", "diffract", "microcode", "plume"] as const;
export type IntricacyFamily = typeof intricacyFamilies[number];
export const isIntricacy = (family: string): family is IntricacyFamily => intricacyFamilies.some(value => value === family);
export const synthesisFamilies = ['estuary', 'excitable', 'sgraffito', 'relay', 'slipstream', 'grain-boundary', 'countermarch', 'overprint', 'avalanche', 'magnetron'] as const;
export type SynthesisFamily = typeof synthesisFamilies[number];
export const isSynthesis = (family: string): family is SynthesisFamily => synthesisFamilies.some(value => value === family);
export const mechanismFamilies = ['shellsort', 'frost', 'rule', 'buoyancy', 'macroblock', 'larsen', 'glyph', 'loupe', 'scanhead', 'interlace'] as const;
export type MechanismFamily = typeof mechanismFamilies[number];
export const isMechanism = (family: string): family is MechanismFamily => mechanismFamilies.some(value => value === family);
/** Absolute-time scores clamp at finite precision horizons; legacy bounds stay unchanged. */
export const timeLimit = (family: string) => (isIntricacy(family) || isSynthesis(family) || isMechanism(family) || isKit(family)) ? 1000000000000 : isEntropy(family) ? 315360000 : 3600;
export function advanceTime(family: string, time: number, delta: number) {
  return isEntropy(family) || isIntricacy(family) || isSynthesis(family) || isMechanism(family) || isKit(family) ? Math.min(timeLimit(family), time + delta) : (time + delta) % 3600;
}
export const isCrisp = (family: string) => family === 'broken-lcd' || isPixelSorter(family) || isDeparture(family) || isDamage(family) || isEntropy(family) || isIntricacy(family) || isSynthesis(family) || isMechanism(family) || isKit(family);
export type Family = 'caustics' | 'phosphor' | 'halftone' | 'ink' | 'iridescence' | 'shafts' | 'aurora' | 'moire' | 'contours' | 'weave' | 'dunes' | 'ripples' | 'starfield' | 'marble' | 'glass' | 'broken-lcd' | PixelSorterFamily | DepartureFamily | DamageFamily | EntropyFamily | IntricacyFamily | SynthesisFamily | MechanismFamily | PatternFamily | RasterFamily | MatterFamily;
export type Backend = 'auto' | 'webgpu' | 'webgl2';
export type Parameters = { scale: number; speed: number; intensity: number; detail: number };
export type Palette = [string, string] | [string, string, string] | [string, string, string, string] | [string, string, string, string, string];
export type PaletteSize = 2 | 3 | 4 | 5;
export type Recipe = {
  schemaVersion: 1; generatorVersion: GeneratorVersion; id: string; name: string;
  kind: 'animated-shader'; family: Family; seed: number; time: number;
  parameters: Parameters; palette: Palette; tags: string[];
  review: 'candidate' | 'accepted';
};
export const controls = {
  scale: { min: 1, max: 12, step: 0.1, label: 'Scale' },
  speed: { min: 0, max: 2, step: 0.05, label: 'Motion' },
  intensity: { min: 0.1, max: 2, step: 0.05, label: 'Intensity' },
  detail: { min: 0, max: 1, step: 0.01, label: 'Detail' },
} as const;
export const families: Record<Family, { name: string; subtitle: string; description: string; detail: string; number: string }> = {
  caustics: { name: 'Caustics', subtitle: 'Light, caught in water.', description: 'Slowly folding ribbons of light meet in a deep, tidal field.', detail: 'Focus', number: 'A01' },
  phosphor: { name: 'Phosphor', subtitle: 'A signal with a pulse.', description: 'A luminous oscilloscope trace, curved glass, and a restless phosphor grille.', detail: 'Scanlines', number: 'A02' },
  halftone: { name: 'Halftone', subtitle: 'Ink that never quite dries.', description: 'Two rotating print screens follow a breathing field of ink and paper.', detail: 'Registration', number: 'A03' },
  ink: { name: 'Ink diffusion', subtitle: 'A bloom without a boundary.', description: 'A suspended pool of pigment grows ragged edges, translucent washes, and dense blue folds.', detail: 'Bleed', number: 'A04' },
  iridescence: { name: 'Iridescence', subtitle: 'Every fold, another color.', description: 'A thin-film study: soft pearlescent color bands slide across a rippling membrane.', detail: 'Film thickness', number: 'A05' },
  shafts: { name: 'Light shafts', subtitle: 'Dust in the afternoon.', description: 'Slanted columns of warm light pass through drifting layers of cool, hazy air.', detail: 'Haze', number: 'A06' },
  aurora: { name: 'Aurora', subtitle: 'The sky, quietly electric.', description: 'Luminous curtains gather into a wavering edge and unravel into fine vertical rays.', detail: 'Curtain folds', number: 'A07' },
  moire: { name: 'Moiré', subtitle: 'Two rhythms, a third pattern.', description: 'Overlapping line screens turn at different rates, revealing broad interference bands.', detail: 'Screen offset', number: 'A08' },
  contours: { name: 'Contours', subtitle: 'A landscape that won’t settle.', description: 'Fine contour lines trace an evolving height field, with shaded, stepped elevations.', detail: 'Contour density', number: 'A09' },
  weave: { name: 'Woven light', subtitle: 'Over, under, in motion.', description: 'Raised warp and weft threads trade places in a gently bending weave with shifting highlights.', detail: 'Thread width', number: 'A10' },
  dunes: { name: 'Dunes', subtitle: 'Written by the wind.', description: 'Broad dune crests advance across warm sand, carrying fine ripples along their slopes.', detail: 'Sand ripples', number: 'A11' },
  ripples: { name: 'Ripples', subtitle: 'Water remembers the rain.', description: 'Three overlapping wave sources send circular ripples through a reflective blue surface.', detail: 'Wave sharpness', number: 'A12' },
  starfield: { name: 'Starfield', subtitle: 'A little further from here.', description: 'Three layers of seeded stars drift at different depths, twinkling over a faint nebula.', detail: 'Star glow', number: 'A13' },
  marble: { name: 'Marble', subtitle: 'Stone with a current.', description: 'Warped mineral ribbons fold together, separating pale stone from fine colored veins.', detail: 'Veining', number: 'A14' },
  glass: { name: 'Stained glass', subtitle: 'A garden of shifting panes.', description: 'Moving Voronoi cells form colored panes with dark seams and softly lit bevels.', detail: 'Seam width', number: 'A15' },
  'broken-lcd': { name: 'Broken LCD', subtitle: 'A signal losing its shape.', description: 'Fast flickering scanlines carry torn lime shapes and lingering blue dither.', detail: 'Signal detail', number: '01' },
  crosscurrent: { name: 'Crosscurrent', subtitle: 'Two currents, one torn signal.', description: 'Opposing row currents pull islands into horizontal ribbons and dithered wakes.', detail: 'Signal detail', number: '02' },
  undertow: { name: 'Undertow', subtitle: 'A signal caught in the curl.', description: 'Curved pixel transport winds torn contour islands into hooked afterimages.', detail: 'Signal detail', number: '03' },
  downpour: { name: 'Downpour', subtitle: 'Color falls through the static.', description: 'Unequal falling rakes carry fragments across a rapidly flickering horizontal carrier.', detail: 'Signal detail', number: '04' },
  faultline: { name: 'Faultline', subtitle: 'The image slips out of alignment.', description: 'Diagonal sorting and local shears split contour masses into displaced shards.', detail: 'Signal detail', number: '05' },
  'rotor': { name: 'Rotor', subtitle: 'An orbit coming apart.', description: 'Eccentric spiral cuts torque through coarse ink, leaving stippled arc fragments.', detail: 'Structure', number: '06' },
  'slingshot': { name: 'Slingshot', subtitle: 'Ribbons under tension.', description: 'Elastic, overlapping ribbons accelerate through changing bends and leave torn color trails.', detail: 'Structure', number: '07' },
  'cell-division': { name: 'Cell division', subtitle: 'A restless membrane.', description: 'Unequal cells exchange space as their membranes erode, brighten and fracture.', detail: 'Structure', number: '08' },
  'shockfront': { name: 'Shockfront', subtitle: 'Every impact starts somewhere new.', description: 'Irregular impacts send broken concentric fronts across a dark, persistent field.', detail: 'Structure', number: '09' },
  'filament': { name: 'Filament', subtitle: 'A live wire without an end.', description: 'Tangled etched strands race through a warped field and accumulate colored traces.', detail: 'Structure', number: '10' },
  'row-collapse': { name: "Row collapse", subtitle: "A row forgets its address.", description: "Unequal horizontal bands buckle, latch and tear into moving combs of pixels.", detail: "Row fracture", number: '11' },
  'column-shear': { name: "Column shear", subtitle: "The columns slide apart.", description: "Vertical needles and broad shutters slip at different rates, leaving interrupted pixel trails.", detail: "Gate density", number: '12' },
  'address-drift': { name: "Address drift", subtitle: "The image reads the wrong memory.", description: "Row and column addresses fold into nested rectangular circuitry, exchanging ink through misrouted junctions.", detail: "Address depth", number: '13' },
  'staircase': { name: "Staircase", subtitle: "A fracture takes the long way.", description: "Uneven stepped fault paths zip diagonally across the panel and drag combed fragments behind them.", detail: "Step density", number: '14' },
  'dead-channel': { name: "Dead channel", subtitle: "Failure spreads through the lattice.", description: "Angular dead zones compete for space while live channels crawl between their eroding edges.", detail: "Channel width", number: '15' },
  'puncture': { name: "Puncture", subtitle: "Pressure finds a center.", description: "Off-center punctures throw torn radial fans through a fast, damaged row carrier.", detail: "Fan fracture", number: '16' },
  'pressure-leak': { name: "Pressure leak", subtitle: "Ink escapes the wound.", description: "Connected pools force their way through branching channels, carrying hard dithered seams and crosshatched wakes.", detail: "Leak width", number: '17' },
  'shatter': { name: "Shatter", subtitle: "Every shard keeps moving.", description: "Unequal polygon fragments slip along their own directions; fractured seams catch bright migrating pixels.", detail: "Shard edges", number: '18' },
  'delamination': { name: "Delamination", subtitle: "Layers lose their registration.", description: "Off-center contour sheets peel into broken crescents and thin raster ladders, each pulled across the next.", detail: "Layer spacing", number: '19' },
  'raster-bloom': { name: "Raster bloom", subtitle: "A pulse meets the grid.", description: "Irregular pressure fronts expand into square-cut petals and torn rings as the panel fights their motion.", detail: "Front fracture", number: '20' },
  'rift': { name: "Rift", subtitle: "The seam chooses another path.", description: "Irregular branching faults tear through unequal plates and drag hard pixel grit into their wakes.", detail: "Fracture width", number: '21' },
  'parcel': { name: "Parcel", subtitle: "Nothing keeps its address.", description: "Unequal rectangular packets collide, exchange pigment and break apart without a repeating tile.", detail: "Packet cut", number: '22' },
  'tangle': { name: "Tangle", subtitle: "Every strand finds a detour.", description: "Interlaced irregular strands knot, split and reconnect as changing currents pull their pixel traces.", detail: "Strand width", number: '23' },
  'spall': { name: "Spall", subtitle: "The surface sheds its skin.", description: "Tapered fragments peel away from moving ruptures and leave stippled chips across the field.", detail: "Fragment cut", number: '24' },
  'dendrite': { name: "Dendrite", subtitle: "A branch becomes a river.", description: "Forked channels etch through uneven pigment reservoirs while local deposits keep diverting their growth.", detail: "Branch density", number: '25' },
  'suture': { name: "Suture", subtitle: "The cut keeps opening.", description: "A wandering zigzag seam breaks into stitched fragments, closes locally and opens somewhere else.", detail: "Seam depth", number: '26' },
  'flock': { name: "Flock", subtitle: "Fragments travel together.", description: "Unequal fragments emerge, accelerate and leave persistent trails in a field whose direction keeps changing.", detail: "Trail bite", number: '27' },
  'palisade': { name: "Palisade", subtitle: "The wall loses its footing.", description: "Irregular ledges and tall broken plates shift through changing column addresses and local shears.", detail: "Ledge depth", number: '28' },
  'alveoli': { name: "Alveoli", subtitle: "The cavities trade places.", description: "Unequal hollow cells erode, merge and replenish with hard pixel membranes and migrating pockets.", detail: "Membrane width", number: '29' },
  'confluence': { name: "Confluence", subtitle: "Every collision changes the map.", description: "Independently born pressure fronts intersect into broken crescents and bright migrating junctions.", detail: "Front width", number: '30' },
  'intaglio': { name: 'Intaglio', subtitle: "Contours cut into the signal.", description: "Nested torn contour terraces slide through fine horizontal incisions and persistent colored wakes.", detail: 'Incision density', number: '31' },
  'braid': { name: 'Braid', subtitle: "Currents knot and unravel.", description: "Interleaved narrow ribbons cross and exchange pixels, combed by independently moving row segments.", detail: 'Incision density', number: '32' },
  'scrim': { name: 'Scrim', subtitle: "A screen within the screen.", description: "Warped mesh apertures stretch and snag while staggered scan stitches expose their changing knots.", detail: 'Incision density', number: '33' },
  'guilloche': { name: 'Guilloche', subtitle: "Engraved currents lose their center.", description: "Eccentric engraved loops fold into dense broken rosettes, crossed by offset horizontal exposures.", detail: 'Incision density', number: '34' },
  'imbricate': { name: 'Imbricate', subtitle: "Every scale carries a scar.", description: "Overlapping scalloped scales shed fine parallel ridges into alternating diagonal currents.", detail: 'Incision density', number: '35' },
  'capillary': { name: 'Capillary', subtitle: "The smallest channels stay alive.", description: "Dense branching microchannels pull pigment through pools and fractured horizontal capillaries.", detail: 'Incision density', number: '36' },
  'palimpsest': { name: 'Palimpsest', subtitle: "One image writes over another.", description: "Two displaced contour maps overwrite each other in local patches, leaving fine crosshatched memory.", detail: 'Incision density', number: '37' },
  'diffract': { name: 'Diffract', subtitle: "The fringes refuse to align.", description: "Unequal warped wavefronts split into dense interference fringes with interrupted raster flicker.", detail: 'Incision density', number: '38' },
  'microcode': { name: 'Microcode', subtitle: "An address becomes a texture.", description: "Nested unequal address cells route fine combs and binary cuts through changing row and column paths.", detail: 'Incision density', number: '39' },
  'relay': { name: "Relay", subtitle: "The trace chooses the next route.", description: "Latched rectangular channels switch between row and column currents as their stored charge changes.", detail: "Address density", number: '44' },
  'slipstream': { name: "Slipstream", subtitle: "A wake becomes a guide.", description: "Curved engraved jets capture neighboring pixels; older wakes switch material between tangential and crossing streams.", detail: "Wake filaments", number: '45' },
  'grain-boundary': { name: "Grain boundary", subtitle: "The seam carries the pressure.", description: "Competing angular domains etch fine terraces; their seams jam and release transported pigment.", detail: "Terrace density", number: '46' },
  'countermarch': { name: "Countermarch", subtitle: "Opposing steps exchange their weight.", description: "Unequal herringbone conveyors move in opposite directions and exchange pigment when their histories disagree.", detail: "Tooth density", number: '47' },
  'overprint': { name: "Overprint", subtitle: "The old mark shifts the new one.", description: "Two skewed mesh registers develop beat patterns; surviving marks determine which register can print again.", detail: "Mesh frequency", number: '48' },
  'avalanche': { name: "Avalanche", subtitle: "A ledge gives way locally.", description: "Terraced stepped deposits hold and release in uneven cascades, leaving incised trails through their previous positions.", detail: "Ledge teeth", number: '49' },
  'magnetron': { name: "Magnetron", subtitle: "Every orbit has an escape.", description: "Offset lobes pull engraved fragments around migrating centers; accumulated change releases them into outward bursts.", detail: "Orbit cuts", number: '50' },
  'estuary': { name: 'Estuary', subtitle: 'The current writes its banks.', description: 'Crossing currents carry engraved sediment; accumulated change diverts pigment into branching distributaries.', detail: 'Channel density', number: '41' },
  'excitable': { name: 'Excitable', subtitle: 'A pulse leaves a refractory wake.', description: 'Etched wavelets move through recovering regions; fresh impacts meet the memory of earlier fronts.', detail: 'Pulse teeth', number: '42' },
  'sgraffito': { name: 'Sgraffito', subtitle: 'The underlayer pushes back.', description: 'Abraded crosshatching exposes another contour system; transported scars decide where new layers take hold.', detail: 'Cut density', number: '43' },
  'plume': { name: 'Plume', subtitle: "Fine barbs ride the current.", description: "Bending feather spines carry hundreds of fine barbs into sheared, stippled trailing wakes.", detail: 'Incision density', number: '40' },
  'shellsort': { name: 'Shellsort', subtitle: "The sort takes longer strides.", description: "Gapped compare/exchange passes drag torn islands into long stepped runs that flip direction band by band.", detail: 'Sort threshold', number: '51' },
  'frost': { name: 'Frost', subtitle: "Every nucleus grows facets.", description: "Directional dilation grows faceted crystal branches from drifting nuclei while local thaws eat them back.", detail: 'Porosity', number: '52' },
  'rule': { name: 'Rule', subtitle: "Three neighbours decide the next row.", description: "Elementary automata cascade down interleaved fields; regional rules change independently and events flip single bits.", detail: 'Rule contrast', number: '53' },
  'buoyancy': { name: 'Buoyancy', subtitle: "Bright pixels rise along the current.", description: "Alternating 2×2 blocks sort their pixels along a curling field, so light streams one way and dark sinks the other.", detail: 'Sort gate', number: '54' },
  'macroblock': { name: 'Macroblock', subtitle: "The motion vectors lost their keyframe.", description: "Blocks copy history through their own motion vectors, smearing across borders with DCT residuals and sparse intra refreshes.", detail: 'Block size', number: '55' },
  'larsen': { name: 'Larsen', subtitle: "The camera is pointed at its own monitor.", description: "Rotating, zooming and folding video feedback turns each arrival into spirals of nearest-neighbor copies.", detail: 'Incision density', number: '56' },
  'glyph': { name: 'Glyph', subtitle: "A terminal that melts as it types.", description: "Mirrored 5×7 glyphs are retyped by staggered cursors while melt zones sort their pixels into drips.", detail: 'Incision density', number: '57' },
  'loupe': { name: 'Loupe', subtitle: "Resolution fails in circles.", description: "Hard-edged lenses crush the moving image into growing mosaic cells; currents tear the enlarged blocks apart.", detail: 'Mosaic size', number: '58' },
  'scanhead': { name: 'Scanhead', subtitle: "Three heads write; every row slips.", description: "Rolling write heads lay down fresh detail while row bands slide and wrap at their own changing speeds.", detail: 'Incision density', number: '59' },
  'interlace': { name: 'Interlace', subtitle: "Two fields, two currents.", description: "Odd and even rows carry different images through different currents, combing every moving edge.", detail: 'Incision density', number: '60' },
  ...patternInfo, ...rasterInfo, ...matterInfo,
};
/** Complete registry, including deprecated recipes for import compatibility. */
export const allPresets: Recipe[] = [
  { schemaVersion: 1, generatorVersion: '1.0.0', id: 'tidal-glass', name: 'Tidal glass', kind: 'animated-shader', family: 'caustics', seed: 284, time: 3.25, parameters: { scale: 4.2, speed: 0.35, intensity: 1.15, detail: 0.62 }, palette: ['#061c25', '#147f81', '#c6f8c6'], tags: ['water', 'luminous', 'ambient'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.0.0', id: 'night-signal', name: 'Night signal', kind: 'animated-shader', family: 'phosphor', seed: 718, time: 3.25, parameters: { scale: 3.5, speed: 0.65, intensity: 1.2, detail: 0.66 }, palette: ['#071a14', '#249455', '#c1ff9d'], tags: ['crt', 'signal', 'analog'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.0.0', id: 'soft-impression', name: 'Soft impression', kind: 'animated-shader', family: 'halftone', seed: 193, time: 3.25, parameters: { scale: 6, speed: 0.3, intensity: 1.1, detail: 0.35 }, palette: ['#e6ddc8', '#d55b39', '#182f3b'], tags: ['print', 'duotone', 'paper'], review: 'candidate' },
  {"schemaVersion": 1, "generatorVersion": "1.1.0", "id": "ink-in-water", "name": "Ink in water", "kind": "animated-shader", "family": "ink", "seed": 12037, "time": 3.25, "parameters": {"scale": 3.7, "speed": 0.28, "intensity": 1.1, "detail": 0.65}, "palette": ["#eee8d8", "#7397a6", "#14314d"], "tags": ["pigment", "organic", "diffusion"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.1.0", "id": "pearl-membrane", "name": "Pearl membrane", "kind": "animated-shader", "family": "iridescence", "seed": 6219, "time": 3.25, "parameters": {"scale": 3.2, "speed": 0.32, "intensity": 1.05, "detail": 0.57}, "palette": ["#202b49", "#c594c7", "#f1cf9a"], "tags": ["thin film", "pearl", "color"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.1.0", "id": "cathedral-air", "name": "Cathedral air", "kind": "animated-shader", "family": "shafts", "seed": 17533, "time": 3.25, "parameters": {"scale": 4.6, "speed": 0.36, "intensity": 1.2, "detail": 0.62}, "palette": ["#101f2b", "#627875", "#efd09a"], "tags": ["light", "haze", "atmosphere"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.1.0", "id": "boreal-curtain", "name": "Boreal curtain", "kind": "animated-shader", "family": "aurora", "seed": 26031, "time": 3.25, "parameters": {"scale": 4.2, "speed": 0.35, "intensity": 1.15, "detail": 0.66}, "palette": ["#080f29", "#743a83", "#83efbd"], "tags": ["sky", "curtain", "luminous"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.1.0", "id": "beating-screens", "name": "Beating screens", "kind": "animated-shader", "family": "moire", "seed": 8793, "time": 3.25, "parameters": {"scale": 4.5, "speed": 0.4, "intensity": 1.05, "detail": 0.55}, "palette": ["#ebe2cf", "#c36d46", "#243b3b"], "tags": ["optical", "lines", "interference"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.1.0", "id": "slow-cartography", "name": "Slow cartography", "kind": "animated-shader", "family": "contours", "seed": 31451, "time": 3.25, "parameters": {"scale": 3.6, "speed": 0.28, "intensity": 1.15, "detail": 0.52}, "palette": ["#243e3c", "#81946d", "#e7d8ab"], "tags": ["terrain", "isoline", "maps"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.1.0", "id": "silk-crossing", "name": "Silk crossing", "kind": "animated-shader", "family": "weave", "seed": 4437, "time": 3.25, "parameters": {"scale": 4.7, "speed": 0.3, "intensity": 1.1, "detail": 0.6}, "palette": ["#172d39", "#ac5f69", "#e3b68a"], "tags": ["textile", "threads", "woven"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.1.0", "id": "wind-written", "name": "Wind written", "kind": "animated-shader", "family": "dunes", "seed": 21401, "time": 3.25, "parameters": {"scale": 3.8, "speed": 0.3, "intensity": 1.1, "detail": 0.58}, "palette": ["#3a302a", "#b27a4f", "#f4d5a2"], "tags": ["sand", "ridges", "landscape"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.1.0", "id": "rain-memory", "name": "Rain memory", "kind": "animated-shader", "family": "ripples", "seed": 11739, "time": 3.25, "parameters": {"scale": 4.2, "speed": 0.6, "intensity": 1.1, "detail": 0.62}, "palette": ["#09233e", "#387c94", "#b5e4df"], "tags": ["water", "rings", "reflection"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.1.0", "id": "slow-orbit", "name": "Slow orbit", "kind": "animated-shader", "family": "starfield", "seed": 55831, "time": 3.25, "parameters": {"scale": 4.6, "speed": 0.3, "intensity": 1.2, "detail": 0.58}, "palette": ["#080d21", "#61406e", "#b7dcf4"], "tags": ["space", "stars", "parallax"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.1.0", "id": "ribbon-stone", "name": "Ribbon stone", "kind": "animated-shader", "family": "marble", "seed": 39123, "time": 3.25, "parameters": {"scale": 3.8, "speed": 0.27, "intensity": 1.1, "detail": 0.6}, "palette": ["#e4e8d3", "#638a7b", "#283b4a"], "tags": ["mineral", "flow", "veins"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.1.0", "id": "glass-garden", "name": "Glass garden", "kind": "animated-shader", "family": "glass", "seed": 48813, "time": 3.25, "parameters": {"scale": 3.8, "speed": 0.4, "intensity": 1.05, "detail": 0.42}, "palette": ["#152e3a", "#548e81", "#ecc67e"], "tags": ["cells", "mosaic", "glass"], "review": "candidate"},
  { schemaVersion: 1, generatorVersion: '1.1.0', id: 'pink-signal-loss', name: 'Chromatic signal loss', kind: 'animated-shader', family: 'broken-lcd', seed: 14562, time: 3.25, parameters: { scale: 2.4, speed: 1.5, intensity: 1.15, detail: 0.62 }, palette: ['#f6f8f5', '#0066ff', '#a5ff32'], tags: ['lcd', 'glitch', 'dither', 'scanlines'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.2.0', id: 'opposing-currents', name: 'Opposing currents', kind: 'animated-shader', family: 'crosscurrent', seed: 23671, time: 3.25, parameters: { scale: 2.6, speed: 1.5, intensity: 1.08, detail: 0.64 }, palette: ['#f4f7ed', '#0066ff', '#bcff39'], tags: ['pixel sorting', 'feedback', 'dither', 'scanlines'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.2.0', id: 'hooked-memory', name: 'Hooked memory', kind: 'animated-shader', family: 'undertow', seed: 38105, time: 3.25, parameters: { scale: 2.5, speed: 1.45, intensity: 1.12, detail: 0.58 }, palette: ['#f7f2ef', '#d63bb6', '#67efb5'], tags: ['pixel sorting', 'feedback', 'dither', 'scanlines'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.2.0', id: 'falling-register', name: 'Falling register', kind: 'animated-shader', family: 'downpour', seed: 4932, time: 3.25, parameters: { scale: 2.8, speed: 1.5, intensity: 1.08, detail: 0.7 }, palette: ['#f1f4f6', '#124dde', '#edfa41'], tags: ['pixel sorting', 'feedback', 'dither', 'scanlines'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.2.0', id: 'slipped-contours', name: 'Slipped contours', kind: 'animated-shader', family: 'faultline', seed: 52177, time: 3.25, parameters: { scale: 2.3, speed: 1.5, intensity: 1.12, detail: 0.6 }, palette: ['#f6f2ee', '#174c52', '#ff79b5'], tags: ['pixel sorting', 'feedback', 'dither', 'scanlines'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.3.0', id: 'eccentric-press', name: 'Eccentric press', kind: 'animated-shader', family: 'rotor', seed: 19873, time: 3.25, parameters: { scale: 2.6, speed: 1.5, intensity: 1.15, detail: 0.57 }, palette: ['#ece3d0', '#ff4b2e', '#1b2432'], tags: ['departures', 'feedback', 'generative', 'kinetic'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.3.0', id: 'tension-field', name: 'Tension field', kind: 'animated-shader', family: 'slingshot', seed: 35719, time: 3.25, parameters: { scale: 2.2, speed: 1.55, intensity: 1.15, detail: 0.58 }, palette: ['#211538', '#ff553e', '#d9fd60'], tags: ['departures', 'feedback', 'generative', 'kinetic'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.3.0', id: 'restless-membrane', name: 'Restless membrane', kind: 'animated-shader', family: 'cell-division', seed: 5823, time: 3.25, parameters: { scale: 2.4, speed: 1.5, intensity: 1.1, detail: 0.62 }, palette: ['#151d29', '#f7e6ae', '#f46468'], tags: ['departures', 'feedback', 'generative', 'kinetic'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.3.0', id: 'successive-impacts', name: 'Successive impacts', kind: 'animated-shader', family: 'shockfront', seed: 46219, time: 3.25, parameters: { scale: 2.1, speed: 1.55, intensity: 1.2, detail: 0.55 }, palette: ['#101520', '#fc6957', '#d7ff4f'], tags: ['departures', 'feedback', 'generative', 'kinetic'], review: 'candidate' },
  { schemaVersion: 1, generatorVersion: '1.3.0', id: 'live-etching', name: 'Live etching', kind: 'animated-shader', family: 'filament', seed: 27643, time: 3.25, parameters: { scale: 2.5, speed: 1.5, intensity: 1.1, detail: 0.64 }, palette: ['#092832', '#ff7559', '#edebc9'], tags: ['departures', 'feedback', 'generative', 'kinetic'], review: 'candidate' },
  {"schemaVersion": 1, "generatorVersion": "1.4.0", "id": "latched-rows", "name": "Row collapse / address failure", "kind": "animated-shader", "family": "row-collapse", "seed": 16383, "time": 3.25, "parameters": {"scale": 2.4, "speed": 1.55, "intensity": 1.15, "detail": 0.63}, "palette": ["#f3f0da", "#ef452c", "#182720"], "tags": ["damaged lcd", "grid only", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.4.0", "id": "slipping-gates", "name": "Column shear / address failure", "kind": "animated-shader", "family": "column-shear", "seed": 37021, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.55, "intensity": 1.15, "detail": 0.57}, "palette": ["#151d33", "#a4ff41", "#747aff"], "tags": ["damaged lcd", "grid only", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.4.0", "id": "misrouted-memory", "name": "Address drift / address failure", "kind": "animated-shader", "family": "address-drift", "seed": 2783, "time": 3.25, "parameters": {"scale": 2.2, "speed": 1.55, "intensity": 1.15, "detail": 0.58}, "palette": ["#e5ebdf", "#006cee", "#f2386a"], "tags": ["damaged lcd", "grid only", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.4.0", "id": "stepped-faults", "name": "Staircase / address failure", "kind": "animated-shader", "family": "staircase", "seed": 48153, "time": 3.25, "parameters": {"scale": 2.4, "speed": 1.55, "intensity": 1.15, "detail": 0.6}, "palette": ["#202424", "#f39b35", "#dfefc4"], "tags": ["damaged lcd", "grid only", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.4.0", "id": "creeping-failure", "name": "Dead channel / address failure", "kind": "animated-shader", "family": "dead-channel", "seed": 14317, "time": 3.25, "parameters": {"scale": 2.8, "speed": 1.55, "intensity": 1.15, "detail": 0.6}, "palette": ["#efe5cf", "#824be9", "#123f44"], "tags": ["damaged lcd", "grid only", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.4.0", "id": "ruptured-polarizer", "name": "Puncture / pressure study", "kind": "animated-shader", "family": "puncture", "seed": 52419, "time": 3.25, "parameters": {"scale": 2.3, "speed": 1.55, "intensity": 1.15, "detail": 0.62}, "palette": ["#eee7d4", "#ee3d7d", "#222550"], "tags": ["damaged lcd", "grid + radial", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.4.0", "id": "capillary-loss", "name": "Pressure leak / pressure study", "kind": "animated-shader", "family": "pressure-leak", "seed": 29641, "time": 3.25, "parameters": {"scale": 2.5, "speed": 1.55, "intensity": 1.15, "detail": 0.55}, "palette": ["#0e2633", "#27ded2", "#f3a9cc"], "tags": ["damaged lcd", "grid + radial", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.4.0", "id": "slipping-shards", "name": "Shatter / pressure study", "kind": "animated-shader", "family": "shatter", "seed": 6179, "time": 3.25, "parameters": {"scale": 2.2, "speed": 1.55, "intensity": 1.15, "detail": 0.61}, "palette": ["#faebcc", "#e74727", "#242d2f"], "tags": ["damaged lcd", "grid + radial", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.4.0", "id": "peeling-register", "name": "Delamination / pressure study", "kind": "animated-shader", "family": "delamination", "seed": 41287, "time": 3.25, "parameters": {"scale": 2.1, "speed": 1.55, "intensity": 1.15, "detail": 0.56}, "palette": ["#222139", "#ffb542", "#baf077"], "tags": ["damaged lcd", "grid + radial", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.4.0", "id": "trapped-fronts", "name": "Raster bloom / pressure study", "kind": "animated-shader", "family": "raster-bloom", "seed": 33193, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.55, "intensity": 1.15, "detail": 0.6}, "palette": ["#e4eedb", "#275ce2", "#e3455e"], "tags": ["damaged lcd", "grid + radial", "pixel transport", "crisp"], "review": "candidate"},

  {"schemaVersion": 1, "generatorVersion": "1.5.0", "id": "restless-faults", "name": "Rift / entropy study", "kind": "animated-shader", "family": "rift", "seed": 39271, "time": 3.25, "parameters": {"scale": 2.5, "speed": 1.6, "intensity": 1.15, "detail": 0.58}, "palette": ["#e8e1c9", "#f24436", "#193e37"], "tags": ["entropy", "no scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.5.0", "id": "unsettled-parcels", "name": "Parcel / entropy study", "kind": "animated-shader", "family": "parcel", "seed": 8251, "time": 3.25, "parameters": {"scale": 2.4, "speed": 1.6, "intensity": 1.15, "detail": 0.55}, "palette": ["#131b32", "#ed795d", "#caf561"], "tags": ["entropy", "no scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.5.0", "id": "unwinding-knots", "name": "Tangle / entropy study", "kind": "animated-shader", "family": "tangle", "seed": 54739, "time": 3.25, "parameters": {"scale": 2.8, "speed": 1.6, "intensity": 1.15, "detail": 0.6}, "palette": ["#ede9d1", "#795bea", "#173f48"], "tags": ["entropy", "no scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.5.0", "id": "shed-fragments", "name": "Spall / entropy study", "kind": "animated-shader", "family": "spall", "seed": 17749, "time": 3.25, "parameters": {"scale": 2.3, "speed": 1.6, "intensity": 1.15, "detail": 0.54}, "palette": ["#211b39", "#f075ae", "#e9e783"], "tags": ["entropy", "no scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.5.0", "id": "wandering-branches", "name": "Dendrite / entropy study", "kind": "animated-shader", "family": "dendrite", "seed": 6331, "time": 3.25, "parameters": {"scale": 2.5, "speed": 1.6, "intensity": 1.15, "detail": 0.57}, "palette": ["#edf1d3", "#148f8a", "#242b45"], "tags": ["entropy", "no scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.5.0", "id": "unfinished-seams", "name": "Suture / entropy study", "kind": "animated-shader", "family": "suture", "seed": 48311, "time": 3.25, "parameters": {"scale": 2.7, "speed": 1.6, "intensity": 1.15, "detail": 0.55}, "palette": ["#132c32", "#f15b3d", "#f2dbaf"], "tags": ["entropy", "no scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.5.0", "id": "migrating-fragments", "name": "Flock / entropy study", "kind": "animated-shader", "family": "flock", "seed": 23917, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.6, "intensity": 1.15, "detail": 0.61}, "palette": ["#eee1d0", "#2374ec", "#ef4977"], "tags": ["entropy", "no scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.5.0", "id": "unmoored-plates", "name": "Palisade / entropy study", "kind": "animated-shader", "family": "palisade", "seed": 57793, "time": 3.25, "parameters": {"scale": 2.3, "speed": 1.6, "intensity": 1.15, "detail": 0.6}, "palette": ["#282733", "#e8b750", "#b7e1cb"], "tags": ["entropy", "no scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.5.0", "id": "exchanging-cavities", "name": "Alveoli / entropy study", "kind": "animated-shader", "family": "alveoli", "seed": 30467, "time": 3.25, "parameters": {"scale": 2.3, "speed": 1.6, "intensity": 1.15, "detail": 0.57}, "palette": ["#f2decb", "#e5614c", "#20443c"], "tags": ["entropy", "no scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.5.0", "id": "unrelated-arrivals", "name": "Confluence / entropy study", "kind": "animated-shader", "family": "confluence", "seed": 11903, "time": 3.25, "parameters": {"scale": 2.4, "speed": 1.6, "intensity": 1.15, "detail": 0.58}, "palette": ["#16283b", "#bdaeef", "#f2cf51"], "tags": ["entropy", "no scanlines", "pixel transport", "crisp"], "review": "candidate"},

  {"schemaVersion": 1, "generatorVersion": "1.6.0", "id": "dense-intaglio", "name": "Intaglio / intricacy study", "kind": "animated-shader", "family": "intaglio", "seed": 32173, "time": 3.25, "parameters": {"scale": 2.7, "speed": 1.5, "intensity": 1.1, "detail": 0.68}, "palette": ["#f3f4e7", "#005dff", "#b5fa38"], "tags": ["intricacy", "scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.6.0", "id": "dense-braid", "name": "Braid / intricacy study", "kind": "animated-shader", "family": "braid", "seed": 17509, "time": 3.25, "parameters": {"scale": 2.5, "speed": 1.5, "intensity": 1.1, "detail": 0.68}, "palette": ["#f5eade", "#ce347d", "#273fe6"], "tags": ["intricacy", "scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.6.0", "id": "dense-scrim", "name": "Scrim / intricacy study", "kind": "animated-shader", "family": "scrim", "seed": 58133, "time": 3.25, "parameters": {"scale": 2.4, "speed": 1.5, "intensity": 1.1, "detail": 0.68}, "palette": ["#e7f0df", "#006e77", "#f15a30"], "tags": ["intricacy", "scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.6.0", "id": "dense-guilloche", "name": "Guilloche / intricacy study", "kind": "animated-shader", "family": "guilloche", "seed": 9471, "time": 3.25, "parameters": {"scale": 2.3, "speed": 1.5, "intensity": 1.1, "detail": 0.68}, "palette": ["#1b2440", "#ef74b3", "#e6f55c"], "tags": ["intricacy", "scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.6.0", "id": "dense-imbricate", "name": "Imbricate / intricacy study", "kind": "animated-shader", "family": "imbricate", "seed": 44237, "time": 3.25, "parameters": {"scale": 2.8, "speed": 1.5, "intensity": 1.1, "detail": 0.68}, "palette": ["#f4edcf", "#1565d8", "#eb573c"], "tags": ["intricacy", "scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.6.0", "id": "dense-capillary", "name": "Capillary / intricacy study", "kind": "animated-shader", "family": "capillary", "seed": 26953, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.68}, "palette": ["#e7f4e7", "#007d73", "#fa6492"], "tags": ["intricacy", "scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.6.0", "id": "dense-palimpsest", "name": "Palimpsest / intricacy study", "kind": "animated-shader", "family": "palimpsest", "seed": 60317, "time": 3.25, "parameters": {"scale": 2.4, "speed": 1.5, "intensity": 1.1, "detail": 0.68}, "palette": ["#ece8ef", "#6551e8", "#f4ac2b"], "tags": ["intricacy", "scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.6.0", "id": "dense-diffract", "name": "Diffract / intricacy study", "kind": "animated-shader", "family": "diffract", "seed": 13841, "time": 3.25, "parameters": {"scale": 2.5, "speed": 1.5, "intensity": 1.1, "detail": 0.68}, "palette": ["#152e34", "#f56139", "#d9ef89"], "tags": ["intricacy", "scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.6.0", "id": "dense-microcode", "name": "Microcode / intricacy study", "kind": "animated-shader", "family": "microcode", "seed": 39719, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.68}, "palette": ["#eef0dc", "#145bea", "#baec46"], "tags": ["intricacy", "scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.6.0", "id": "dense-plume", "name": "Plume / intricacy study", "kind": "animated-shader", "family": "plume", "seed": 22483, "time": 3.25, "parameters": {"scale": 2.5, "speed": 1.5, "intensity": 1.1, "detail": 0.68}, "palette": ["#ece6d5", "#d64068", "#154f68"], "tags": ["intricacy", "scanlines", "pixel transport", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "coupled-estuary", "name": "Estuary / synthesis study", "kind": "animated-shader", "family": "estuary", "seed": 42433, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.66}, "palette": ["#edf2df", "#006bff", "#b9ef36"], "tags": ["synthesis", "coupled feedback", "crisp", "pixel transport"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "coupled-excitable", "name": "Excitable / synthesis study", "kind": "animated-shader", "family": "excitable", "seed": 7139, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.66}, "palette": ["#182c3d", "#ff6759", "#e8edb2"], "tags": ["synthesis", "coupled feedback", "crisp", "pixel transport"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "coupled-sgraffito", "name": "Sgraffito / synthesis study", "kind": "animated-shader", "family": "sgraffito", "seed": 58217, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.66}, "palette": ["#efe6d1", "#d64071", "#1f625b"], "tags": ["synthesis", "coupled feedback", "crisp", "pixel transport"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "coupled-relay", "name": "Relay / synthesis study", "kind": "animated-shader", "family": "relay", "seed": 14833, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.66}, "palette": ["#e7ecd5", "#e63e63", "#1553be"], "tags": ["synthesis", "coupled feedback", "crisp", "pixel transport", "grid only"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "coupled-slipstream", "name": "Slipstream / synthesis study", "kind": "animated-shader", "family": "slipstream", "seed": 52791, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.66}, "palette": ["#152a35", "#f46b38", "#d4ee91"], "tags": ["synthesis", "coupled feedback", "crisp", "pixel transport"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "coupled-grain-boundary", "name": "Grain boundary / synthesis study", "kind": "animated-shader", "family": "grain-boundary", "seed": 9367, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.66}, "palette": ["#f1e6d0", "#655be5", "#23695d"], "tags": ["synthesis", "coupled feedback", "crisp", "pixel transport"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "coupled-countermarch", "name": "Countermarch / synthesis study", "kind": "animated-shader", "family": "countermarch", "seed": 31871, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.66}, "palette": ["#20283e", "#fa744e", "#e7ecb8"], "tags": ["synthesis", "coupled feedback", "crisp", "pixel transport", "grid only"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "coupled-overprint", "name": "Overprint / synthesis study", "kind": "animated-shader", "family": "overprint", "seed": 48713, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.66}, "palette": ["#ecead8", "#006cea", "#e8577b"], "tags": ["synthesis", "coupled feedback", "crisp", "pixel transport"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "coupled-avalanche", "name": "Avalanche / synthesis study", "kind": "animated-shader", "family": "avalanche", "seed": 27149, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.66}, "palette": ["#eee9d0", "#bc3f79", "#224e50"], "tags": ["synthesis", "coupled feedback", "crisp", "pixel transport", "grid only"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "coupled-magnetron", "name": "Magnetron / synthesis study", "kind": "animated-shader", "family": "magnetron", "seed": 61223, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.66}, "palette": ["#142d38", "#ff7052", "#e0f486"], "tags": ["synthesis", "coupled feedback", "crisp", "pixel transport"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "long-strides", "name": "Shellsort / mechanism study", "kind": "animated-shader", "family": "shellsort", "seed": 24611, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.6}, "palette": ["#f2efe6", "#ff3d6e", "#1b1f4b"], "tags": ["mechanism", "pixel sorting", "scanlines", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "faceted-growth", "name": "Frost / mechanism study", "kind": "animated-shader", "family": "frost", "seed": 50923, "time": 3.25, "parameters": {"scale": 2.4, "speed": 1.5, "intensity": 1.15, "detail": 0.45}, "palette": ["#e8eef2", "#3d5afe", "#0a1a2f"], "tags": ["mechanism", "morphology", "growth", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "cascading-rules", "name": "Rule / mechanism study", "kind": "animated-shader", "family": "rule", "seed": 7349, "time": 3.25, "parameters": {"scale": 2.3, "speed": 1.5, "intensity": 1.0, "detail": 0.6}, "palette": ["#efeadb", "#ff6a1f", "#14213d"], "tags": ["mechanism", "automaton", "scanlines", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "rising-pixels", "name": "Buoyancy / mechanism study", "kind": "animated-shader", "family": "buoyancy", "seed": 41161, "time": 3.25, "parameters": {"scale": 2.5, "speed": 1.5, "intensity": 1.1, "detail": 0.35}, "palette": ["#1d1233", "#ffd23f", "#ff5fa2"], "tags": ["mechanism", "pixel sorting", "2d sort", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "lost-keyframe", "name": "Macroblock / mechanism study", "kind": "animated-shader", "family": "macroblock", "seed": 18839, "time": 3.25, "parameters": {"scale": 2.5, "speed": 1.5, "intensity": 1.1, "detail": 0.5}, "palette": ["#e9ecef", "#00c46a", "#7a2cf0"], "tags": ["mechanism", "datamosh", "blocks", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "monitor-loop", "name": "Larsen / mechanism study", "kind": "animated-shader", "family": "larsen", "seed": 62207, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.62}, "palette": ["#f3ede0", "#ff2d2d", "#111111"], "tags": ["mechanism", "video feedback", "radial", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "melting-terminal", "name": "Glyph / mechanism study", "kind": "animated-shader", "family": "glyph", "seed": 9043, "time": 3.25, "parameters": {"scale": 2.5, "speed": 1.5, "intensity": 1.05, "detail": 0.6}, "palette": ["#0b2a1f", "#ffb000", "#b8ff9c"], "tags": ["mechanism", "text", "scanlines", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "crushed-lenses", "name": "Loupe / mechanism study", "kind": "animated-shader", "family": "loupe", "seed": 35527, "time": 3.25, "parameters": {"scale": 2.5, "speed": 1.5, "intensity": 1.1, "detail": 0.55}, "palette": ["#f7f3ea", "#2a6cff", "#ff4f2e"], "tags": ["mechanism", "mosaic", "radial", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "rolling-writes", "name": "Scanhead / mechanism study", "kind": "animated-shader", "family": "scanhead", "seed": 28453, "time": 3.25, "parameters": {"scale": 2.6, "speed": 1.5, "intensity": 1.1, "detail": 0.66}, "palette": ["#e8f1f5", "#ff2e97", "#003049"], "tags": ["mechanism", "rolling shutter", "scanlines", "crisp"], "review": "candidate"},
  {"schemaVersion": 1, "generatorVersion": "1.7.0", "id": "combed-fields", "name": "Interlace / mechanism study", "kind": "animated-shader", "family": "interlace", "seed": 46099, "time": 3.25, "parameters": {"scale": 2.5, "speed": 1.5, "intensity": 1.1, "detail": 0.62}, "palette": ["#171a2b", "#3cf2c8", "#ff7a45"], "tags": ["mechanism", "interlace", "scanlines", "crisp"], "review": "candidate"},

  ...patternPresets, ...rasterPresets, ...matterPresets,
];
/** Browsing order: the ten user-endorsed crisp studies, then damage, entropy, intricacy, synthesis, mechanism, pattern, raster and matter studies. */
export const presets = allPresets.filter(recipe => isCrisp(recipe.family));
export const deprecatedPresets = allPresets.filter(recipe => !isCrisp(recipe.family));

const object = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value);
function range(value: unknown, min: number, max: number, field: string) {
  if (typeof value !== 'number' || !Number.isFinite(value) || value < min || value > max) throw new Error(`${field} must be between ${min} and ${max}.`);
  return value;
}
export function validateRecipe(value: unknown): Recipe {
  if (!object(value)) throw new Error('Expected a recipe object.');
  if (value.schemaVersion !== RECIPE_VERSION || typeof value.generatorVersion !== 'string' || !generatorVersions.includes(value.generatorVersion)) throw new Error('Unsupported recipe or generator version.');
  if (value.kind !== 'animated-shader') throw new Error('Expected an animated-shader recipe.');
  if (typeof value.family !== 'string' || !Object.hasOwn(families, value.family)) throw new Error('Unknown effect family.');
  if (value.generatorVersion === '1.0.0' && !['caustics', 'phosphor', 'halftone'].includes(value.family)) throw new Error('This family requires generator version 1.1.0.');
  if (isPixelSorter(value.family) && !['1.2.0', '1.3.0', '1.4.0', '1.5.0', '1.6.0', '1.7.0', '1.8.0', '1.9.0'].includes(String(value.generatorVersion))) throw new Error('This family requires generator version 1.2.0.');
  if (isDeparture(value.family) && !['1.3.0', '1.4.0', '1.5.0', '1.6.0', '1.7.0', '1.8.0', '1.9.0'].includes(String(value.generatorVersion))) throw new Error('This family requires generator version 1.3.0.');
  if (isDamage(value.family) && !['1.4.0', '1.5.0', '1.6.0', '1.7.0', '1.8.0', '1.9.0'].includes(String(value.generatorVersion))) throw new Error('This family requires generator version 1.4.0.');
  if (isEntropy(value.family) && !['1.5.0', '1.6.0', '1.7.0', '1.8.0', '1.9.0'].includes(String(value.generatorVersion))) throw new Error('This family requires generator version 1.5.0.');
  if (isIntricacy(value.family) && !['1.6.0', '1.7.0', '1.8.0', '1.9.0'].includes(String(value.generatorVersion))) throw new Error('This family requires generator version 1.6.0.');
  if (isMechanism(value.family) && !['1.7.0', '1.8.0', '1.9.0'].includes(String(value.generatorVersion))) throw new Error('This family requires generator version 1.7.0.');
  if (isSynthesis(value.family) && !['1.7.0', '1.8.0', '1.9.0'].includes(String(value.generatorVersion))) throw new Error('This family requires generator version 1.7.0.');
  if (isKit(value.family) && value.generatorVersion !== '1.9.0') throw new Error('This family requires generator version 1.9.0.');
  if (typeof value.id !== 'string' || !/^[a-z0-9][a-z0-9-]{0,63}$/.test(value.id)) throw new Error('Recipe ID must use 1–64 lowercase letters, numbers or hyphens.');
  if (typeof value.name !== 'string' || !value.name.trim() || value.name.length > 80) throw new Error('Recipe name must contain 1–80 characters.');
  const seed = range(value.seed, 0, 65535, 'Seed');
  if (!Number.isInteger(seed)) throw new Error('Seed must be an integer.');
  const time = range(value.time, 0, timeLimit(value.family), 'Time');
  if (!object(value.parameters)) throw new Error('Missing parameters.');
  const parameters = {} as Parameters;
  for (const [key, spec] of Object.entries(controls)) parameters[key as keyof Parameters] = range(value.parameters[key], spec.min, spec.max, key);
  if (!Array.isArray(value.palette) || (value.palette.length < 2 || value.palette.length > 5) || !Array.from(value.palette).every(c => typeof c === 'string' && /^#[0-9a-f]{6}$/i.test(c))) throw new Error('Palette needs two to five six-digit hex colors.');
  if (value.palette.length !== 3 && value.generatorVersion !== '1.8.0' && value.generatorVersion !== '1.9.0') throw new Error('Two, four and five colors require generator version 1.8.0.');
  if (!Array.isArray(value.tags) || value.tags.length > 8 || !value.tags.every(t => typeof t === 'string' && t.length > 0 && t.length <= 32)) throw new Error('Use up to eight short tags.');
  if (value.review !== 'candidate' && value.review !== 'accepted') throw new Error('Invalid review status.');
  return { schemaVersion: 1, generatorVersion: value.generatorVersion as GeneratorVersion, kind: 'animated-shader', id: value.id, name: value.name.trim(), family: value.family as Family, seed, time, parameters, palette: [...value.palette] as Recipe['palette'], tags: [...value.tags], review: value.review };
}
export function parseRecipe(json: string): Recipe {
  if (json.length > 16384) throw new Error('Recipe is too large (16 KB maximum).');
  return validateRecipe(JSON.parse(json));
}
export const serializeRecipe = (recipe: Recipe) => JSON.stringify(validateRecipe(recipe), null, 2) + '\n';
export function variation(base: Recipe, seed: number): Recipe {
  const random = (salt: number) => { let x = Math.imul(seed + salt, 0x45d9f3b); x = Math.imul(x ^ (x >>> 16), 0x45d9f3b); return ((x ^ (x >>> 16)) >>> 0) / 4294967296; };
  return validateRecipe({ ...base, id: `${base.family}-${seed}`, name: `${families[base.family].name} · ${seed}`, seed, review: 'candidate', parameters: { ...base.parameters, scale: +(2 + random(17) * 7).toFixed(1), detail: +(0.2 + random(51) * 0.7).toFixed(2) } });
}
